### ISSUE TITLE
Revisit behaviour and ingest workflow for CLAW

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_solution_pack_oralhistories#110]
When we consider migration pathway to CLAW, revisit ingest behaviour, notably the accepted file formats

**Comment by kstapelfeldt** [comment]
This is a large undertaking we have been discussing that will likely require a project plan, MVP specification, and massive refactoring. Closing this now in favour of a CLAW project label that will be introduced once we have our ducks aligned.
