### ISSUE TITLE
transcript viewer speaker name & transcript content overlapping

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_solution_pack_oralhistories#111]
fix this:
<img width="1198" alt="screen shot 2017-10-23 at 09 19 08" src="https://user-images.githubusercontent.com/2915770/31891092-4f894504-b7d3-11e7-876d-cb54957c3060.png">

to this:
<img width="1200" alt="screen shot 2017-10-23 at 09 18 57" src="https://user-images.githubusercontent.com/2915770/31891097-528a7ca0-b7d3-11e7-8a6e-30346b141156.png">

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/Islandora-Labs/islandora_solution_pack_oralhistories/pull/118 (merged with commit 442352e2d0cd1ce7c1272bbc94372bb08e6305ea.)
