### ISSUE TITLE
Add isset checks to certain params in template.

### ISSUE THREAD

**Issue by ryanbrinn** [digitalutsc/islandora_solution_pack_oralhistories#122]
Template files are making assumptions about present datastrams that are violated by running derivatives in separate processes, as is done with gearman. 
Example:
    Notice: Undefined index: tn in include() (line 5 of /var/www/drupal7/sites/all/modules/islandora_solution_pack_oralhistories/theme/islandora-html5-video-stack.tpl.php).
    Notice: Undefined index: url in include() (line 6 of /var/www/drupal7/sites/all/modules/islandora_solution_pack_oralhistories/theme/islandora-html5-video-stack.tpl.php).
    Notice: Undefined index: mime in include() (line 6 of /var/www/drupal7/sites/all/modules/islandora_solution_pack_oralhistories/theme/islandora-html5-video-stack.tpl.php).

I've created a pull here: https://github.com/Islandora-Labs/islandora_solution_pack_oralhistories/pull/121 which will add an isset check to the affected params so it will fail gracefully.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/Islandora-Labs/islandora_solution_pack_oralhistories/pull/121 (merged with commit https://github.com/Islandora-Labs/islandora_solution_pack_oralhistories/commit/f586562418bbc3545957a453ce6315a098d373de).  Thank you @ryanbrinn for your contribution.
