### ISSUE TITLE
batch ingest oral histories

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_solution_pack_oralhistories#129]
use case request from university of texas auston (briscoe). have about 700 oral histories and want to migrate over from one system to another. possible resolution is to use islandora multi importer.

**Comment by kimpham54** [comment]
@MarcusBarnes to send a message to briscoe about the islandora multi importer option

**Comment by MarcusBarnes** [comment]
N.B:  This issue is basically that found within the discussion of issue https://github.com/Islandora-Labs/islandora_solution_pack_oralhistories/issues/1.

**Comment by MarcusBarnes** [comment]
I've reached out to a user of the Oral History Solution Pack.  They have confirmed that they have used [Islandora Multi-Importer](https://github.com/mnylc/islandora_multi_importer) to batch ingest oral history objects.   It would be good to provide some sort of documentation on basic usage in the [Content and Ingesting section of the wiki](https://github.com/Islandora-Labs/islandora_solution_pack_oralhistories/wiki#content-and-ingesting).

**Comment by wpwentzell** [comment]
I agree on some documentation for a batch ingest for this module that captures the transcripts will be extremely helpful.

**Comment by MarcusBarnes** [comment]
Closing this issue and moving it to documentation issue https://github.com/Islandora-Labs/islandora_solution_pack_oralhistories/issues/131.
