### ISSUE TITLE
Transcript Edit form results in invalid XML

### ISSUE THREAD

**Issue by timtomch** [digitalutsc/islandora_solution_pack_oralhistories#134]
Hello. I've noted that when editing an XML transcript file using the front end edit form and saving, it adds an empty "orphan" <cue/> tag at the top. This breaks transcript functionality and throws the error below. The issue can be resolved by manually fixing the transcript XML datastream, removing the extra <cue/> tag, and replacing the datastream. Can someone replicate the problem?

Until the invalid XML is fixed, this error is displayed on the object page every time it's accessed:

> Notice: Undefined offset: 7 in islandora_oralhistories_transcripts_ui_transcript() (line 175 of /var/www/drupal7/sites/all/modules/islandora_solution_pack_oralhistories/includes/utilities.inc).
    Notice: Undefined offset: 7 in islandora_oralhistories_transcripts_ui_transcript() (line 176 of /var/www/drupal7/sites/all/modules/islandora_solution_pack_oralhistories/includes/utilities.inc).
    Notice: Undefined offset: 7 in islandora_oralhistories_transcripts_ui_transcript() (line 181 of /var/www/drupal7/sites/all/modules/islandora_solution_pack_oralhistories/includes/utilities.inc).
    Notice: Undefined offset: 7 in islandora_oralhistories_transcripts_ui_transcript() (line 181 of /var/www/drupal7/sites/all/modules/islandora_solution_pack_oralhistories/includes/utilities.inc).
    Notice: Undefined offset: 7 in islandora_oralhistories_transcripts_ui_transcript() (line 186 of /var/www/drupal7/sites/all/modules/islandora_solution_pack_oralhistories/includes/utilities.inc).
    Notice: Undefined offset: 7 in islandora_oralhistories_transcripts_ui_transcript() (line 175 of /var/www/drupal7/sites/all/modules/islandora_solution_pack_oralhistories/includes/utilities.inc).
    Notice: Undefined offset: 7 in islandora_oralhistories_transcripts_ui_transcript() (line 176 of /var/www/drupal7/sites/all/modules/islandora_solution_pack_oralhistories/includes/utilities.inc).
    Notice: Undefined offset: 7 in islandora_oralhistories_transcripts_ui_transcript() (line 181 of /var/www/drupal7/sites/all/modules/islandora_solution_pack_oralhistories/includes/utilities.inc).
    Notice: Undefined offset: 7 in islandora_oralhistories_transcripts_ui_transcript() (line 181 of /var/www/drupal7/sites/all/modules/islandora_solution_pack_oralhistories/includes/utilities.inc).
    Notice: Undefined offset: 7 in islandora_oralhistories_transcripts_ui_transcript() (line 186 of /var/www/drupal7/sites/all/modules/islandora_solution_pack_oralhistories/includes/utilities.inc).

(offset will vary depending on the number of cues in the transcript file)

**Comment by kimpham54** [comment]
likely an issue with https://github.com/Islandora-Labs/islandora_solution_pack_oralhistories/blob/7.x/includes/transcript.edit.form.inc#L106

**Comment by MarcusBarnes** [comment]
@timtomch Would please check whether this recent pull-request https://github.com/Islandora-Labs/islandora_solution_pack_oralhistories/pull/135 resolves the issue for you?

**Comment by timtomch** [comment]
@MarcusBarnes thank you, yes I tested it and it does indeed resolve the issue. I can close it now. Thanks!
