### ISSUE TITLE
deprecated code in transcript_ui?

### ISSUE THREAD

**Issue by mdemers** [digitalutsc/islandora_solution_pack_oralhistories#144]
Updating to php 7.1+ breaks things. I get the following fatal error when displaying an oral history object

`Error: [] operator not supported for strings in theme_transcripts_ui_tcu_tier() (line 66 of /var/www/drupal7/sites/all/modules/transcripts_ui/theme/transcripts_ui.theme.inc)`.

It points to this function in particular. I think $vars isn't being set as an array? 
```
function theme_transcripts_ui_tcu_tier($vars)
{
    $vars['classes'][] = 'tier';
    $vars['classes'][] = 'active';
    $classes = implode(' ', $vars['classes']);
    $out = "<div data-tier='{$vars['tier_name']}' class='$classes'>{$vars['tier_text']}</div>";
    return $out;
}
```
I'm afraid I don't know enough PHP to be of more help.

**Comment by mdemers** [comment]
Oh. Maybe I know more than I thought. Dropping `$vars['classes'] = array();` in the top of that function may have taken care of the problem. Will need some more testing. I can submit a pull request if needed, but someone who knows what they're doing should probably audit this stuff for more of these php migration problems.

**Comment by MarcusBarnes** [comment]
@mdemers Thanks.  We're updating our Travis CI builds to include PHP 7.1.   The Travis CI builds that include  PHP 7.1 should fail when an issue such as you reported is present.   We'll then go back and fix the issue you reported and any others we detect.

**Comment by MarcusBarnes** [comment]
@mdemers The following merged pull-request https://github.com/Islandora-Labs/islandora_solution_pack_oralhistories/pull/146 should resolve the specific error mentioned in comment https://github.com/Islandora-Labs/islandora_solution_pack_oralhistories/issues/144#issue-424255227.     The relevant commit is https://github.com/Islandora-Labs/islandora_solution_pack_oralhistories/commit/44471b9b749b54ff8d63b4ca9f7c49a05cc96fbe.   There is partial success with the Travis CI builds, but some modifications still need to be done before it works as desired.  @mdemers Would you please confirm that the changes resolves the specific error you were encountering?

**Comment by mdemers** [comment]
Yes, that fixed it. Thanks.
