### ISSUE TITLE
Remove annotation code

### ISSUE THREAD

**Issue by MarcusBarnes** [digitalutsc/islandora_solution_pack_oralhistories#17]
Annotation capabilities are being developed in a new module (https://github.com/digitalutsc/islandora_web_annotations).  Clean out annotation related code as appropriate.

**Comment by MarcusBarnes** [comment]
Initial work is in branch [issue-17](https://github.com/digitalutsc/islandora_solution_pack_oralhistories/tree/issue-17).  Much more to cleanup to do.

**Comment by Natkeeran** [comment]
Tested by applying the PR to existing OH installation.  Then running the module update.  Also did a brief code review.

*  it prompted to update
* It removed annotation related config option
* The db entries are removed (mysql --user=root --password=islandora -> SELECT * FROM variable WHERE name ='islandora_oralhistories_annotation_tab_display';)

Looks good.  Nice work.  Thank you @MarcusBarnes.
