### ISSUE TITLE
Change default teirs and speaker names in transcript UI submodule

### ISSUE THREAD

**Issue by MarcusBarnes** [digitalutsc/islandora_solution_pack_oralhistories#30]
Pinedrop's [transcript UI](https://github.com/pinedrop/transcripts_ui) provides [default tiers](https://github.com/digitalutsc/islandora_solution_pack_oralhistories/blob/master/transcripts_ui/transcripts_ui.admin.inc#L12) and [speaker names](https://github.com/digitalutsc/islandora_solution_pack_oralhistories/blob/master/transcripts_ui/transcripts_ui.admin.inc#L25).    These defaults appear to be related to the projects that Transcript UI is used with by Pinedrop.  

In order to speed testing, the suggestion is to update the defaults to the tiers and speakers used for the fixtures, namely:

Default Tiers:
-  or_transcript|Transcript
-  or_translation|Translation

Default Speaker Names:
 - or_speaker|Speaker
 - or_solespeaker|Speaker

**Comment by Natkeeran** [comment]
This PR https://github.com/digitalutsc/islandora_solution_pack_oralhistories/pull/31 addresses this issue.
