### ISSUE TITLE
Typo in interface documentation

### ISSUE THREAD

**Issue by kstapelfeldt** [digitalutsc/islandora_solution_pack_oralhistories#33]
"By default, the trascript will be displayed beneath the media object." should read "By default, the transcript will be displayed beneath the media object."

**Comment by MarcusBarnes** [comment]
@kstapelfeldt Please feel free to merge the pull-request if it looks good.  Thank you.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/digitalutsc/islandora_solution_pack_oralhistories/pull/35 (merged with https://github.com/digitalutsc/islandora_solution_pack_oralhistories/commit/464e72ac7c7ec38702f594a6ed50f76b50dffc4f).
