### ISSUE TITLE
After editing a cue in Oral History Solution Pack, can't exit form

### ISSUE THREAD

**Issue by kstapelfeldt** [digitalutsc/islandora_solution_pack_oralhistories#34]
Steps to reproduce: 
1. Navigate to Manage>Datastreams>Edit. Make and submit an edit.
2. Receive a confirmation that the datastream is updated, but there is no way back to the object without navigating from the top collection object. Cannot navigate back in browser. 

How hard would it be to redirect a user back to the object after the edit was complete?

**Comment by MarcusBarnes** [comment]
I've been able to reproduce.  The aim should be to make the behavior similar to what happens when editing the MODS datastream.

**Comment by MarcusBarnes** [comment]
This issue may be related to a theme warning that is appearing in the log: "Theme hook islandora_oralhistories_transcript_edit_form not found."

**Comment by kstapelfeldt** [comment]
Kirsta and @MarcusBarnes to retest to see if this behaviour is still there (test with and without overlay?)

**Comment by MarcusBarnes** [comment]
@kstapelfeldt I'm getting the same behavior as before in my 7.x-1.9 dev VM.  In Firefox, the browser back button brings me back to the datastreams management page for the object.

**Comment by Natkeeran** [comment]
This is a challenging issue that anticipated.  The expected drupal_goto is not working in this situation.  

This PR https://github.com/digitalutsc/islandora_solution_pack_oralhistories/tree/issue_34 addresses this issue partially.  It navigates back to the object after editing the datastream (in the inline form and for the ajax form).  It redirects to the object with notification saying the datastream is updated.  But, the user still has to reload the page to see the changes reflected in the transcript.  

My assumption is that this is a timing issue.  We get the transcript display from solr.  It takes, even in the VM bit of time to index.  We can put an arbitrary time delay, but that is not a deterministic solution.

**Comment by MarcusBarnes** [comment]
Initially addressed in pull-request https://github.com/digitalutsc/islandora_solution_pack_oralhistories/pull/76 (merged with commit https://github.com/digitalutsc/islandora_solution_pack_oralhistories/commit/d04f0a78ad0889ae1201af7e51e9c720f27c978d).   The merged solution improves the behaviour.  If additional changes need to be made, we can either reopen this issue or create a separate specific issue(s).   Thank you.
