### ISSUE TITLE
When the "Enable transcript display" option is not set, completely hide the transcript tab and area.

### ISSUE THREAD

**Issue by MarcusBarnes** [digitalutsc/islandora_solution_pack_oralhistories#37]
When the "Enable transcript display" option is not set, a tab with no content to display is shown.  This can be confusing.
![image](https://cloud.githubusercontent.com/assets/938274/24005144/981f86ea-0a3e-11e7-8187-6b9b7f60d0e1.png)
When the "Enable transcript display" option is not set, completely hide the transcript tab and area.

**Comment by Natkeeran** [comment]
This PR: https://github.com/digitalutsc/islandora_solution_pack_oralhistories/pull/38 addresses this issue.  Thanks Marcus.
