### ISSUE TITLE
Edit function

### ISSUE THREAD

**Issue by petermacdonald** [digitalutsc/islandora_solution_pack_oralhistories#4]
I have everything in the Oral Histories module working now, except for the "Edit" function.

When I click "Edit" I get a spinning "Loading..." symbol and an "AJAX HTTP error":

"Fatal error: Call to a member function children() on a non-object in ...//transcript.edit.form.inc on line 51."

If the "Edit" function should be working, I'll try to fix it on my own, but if the "Edit" function is still under development, I'll just disable it for now?

Thank you,
Peter MacDonald

**Comment by Natkeeran** [comment]
@petermacdonald  Thank you for posting the issue.  

We are currently reviewing the issues related to this module.  Yes, the edit button for transcript should work.  

I am unable to reproduce the issue as you described with the latest build.

**Comment by MarcusBarnes** [comment]
@petermacdonald Thank you.  This has been addressed as of commit 0909208d07061cb95aa47263e833a31eec65919b.
