### ISSUE TITLE
Add bootstrap required for oh as default

### ISSUE THREAD

**Issue by Natkeeran** [digitalutsc/islandora_solution_pack_oralhistories#41]
Currently oh module assumes that the user is using a bootstrap theme.  This is probably not the case for general users.  We have a custom bootstrap css build targeting  oh module elements that gets applied for oh.  Initially this was made configurable.  This config needs to be in place by default to ease installation.

**Comment by MarcusBarnes** [comment]
This has been addressed in pull-request https://github.com/digitalutsc/islandora_solution_pack_oralhistories/pull/42 (merged with commit https://github.com/digitalutsc/islandora_solution_pack_oralhistories/commit/5e782fa48e6f0e2f7d351f41d02d82cf1915c67a).
