### ISSUE TITLE
ingest of oral history with transcript creates multiple captions

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_solution_pack_oralhistories#44]
Description
When an oral history is ingested with a transcript, duplicate caption options are created. Only one caption option works.

Steps to reproduce
1. add an object to a collection (oral history content model)
2. add video + 1 oral history transcript

You should see the following:
![screen shot 2017-04-04 at 09 48 21](https://cloud.githubusercontent.com/assets/2915770/24659927/1d5fd080-191c-11e7-9138-191a4240fe5a.png)

Expected behaviour
You should only see one caption option, and when you select the option it should display the closed captioning.

**Comment by MarcusBarnes** [comment]
@kimpham54 Would you please send the transcript (and video) so that we can reproduce.  Thank you.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/digitalutsc/islandora_solution_pack_oralhistories/pull/50 (merged with commit https://github.com/digitalutsc/islandora_solution_pack_oralhistories/commit/afdb36449706aa6e0c6325b201457da381e6faa6).
