### ISSUE TITLE
side by side display + video controls + web annotations

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_solution_pack_oralhistories#45]
Side by side display of viewer does not show the video controls (or web annotation controls)

Steps to reproduce:
in the Oral History configuration, select " Display media and transcript side-by-side", try to play the video and use normal video playback functions

**Comment by MarcusBarnes** [comment]
Do we know of any installations that use the side-by-side display?  If this feature is not actively used, I wonder if we can deprecate the functionality.

**Comment by kimpham54** [comment]
Not that I know of - if we want to consider deprecation, we can post to the Islandora google group just to be sure.

**Comment by kimpham54** [comment]
@MarcusBarnes @kstapelfeldt : @Natkeeran mentioned that he saw a couple of institutions using side by side display. Something to discuss in the next DSU meeting (my regrets)

**Comment by mkudzia** [comment]
FWIW I don't know of anyone using side-by-side either -- I think checking in with the Islandora google group is a great idea.

**Comment by kstapelfeldt** [comment]
@kimpham54 sending a notice on google list today

**Comment by kstapelfeldt** [comment]
Need to note this as an untested feature in the release documentation.

**Comment by kstapelfeldt** [comment]
fully deprecate and delete in the next release and include in the release notes. Change wiki documentation to reflect the removal of this feature.

**Comment by kstapelfeldt** [comment]
A last call was put out on google list. We'll change this approach if necessary based on any responses.

**Comment by MarcusBarnes** [comment]
Waiting on the results of the review of pull-request https://github.com/Islandora-Labs/islandora_solution_pack_oralhistories/pull/115 before closing this issue.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request #115 (merged with commit 8a5de32565f6282fdc14d547b063d1fc700e97fb).
