### ISSUE TITLE
Provide .install file for Transcript UI submodule

### ISSUE THREAD

**Issue by MarcusBarnes** [digitalutsc/islandora_solution_pack_oralhistories#46]
Provide a .install file for the Transcript UI submodule.  In particular, implement hook_install to install the default configuration variables and hook_uninstall to delete these variables.

Once complete, consider making appropriate modifications so that the file can be provided considered for inclusion in https://github.com/pinedrop/transcripts_ui.

**Comment by Natkeeran** [comment]
This PR: https://github.com/digitalutsc/islandora_solution_pack_oralhistories/pull/48 addresses this issue.  Works as expected.
