### ISSUE TITLE
Interface Wording Change

### ISSUE THREAD

**Issue by kstapelfeldt** [digitalutsc/islandora_solution_pack_oralhistories#51]
<img width="218" alt="screen shot 2017-04-20 at 2 18 35 pm" src="https://cloud.githubusercontent.com/assets/467898/25246691/6caf8cfe-25d6-11e7-96b1-2c324301323e.png">

Users are likely to believe that multiple users will appear in the lower 'Speaker Names' panel depicted in the screenshot. Recommend changing the header "Speaker Names" to read "Toggle speaker names on/off"

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/digitalutsc/islandora_solution_pack_oralhistories/pull/52 (merged with commit https://github.com/digitalutsc/islandora_solution_pack_oralhistories/commit/485055580ee3e0342fc0eac52100ba6912e9b2d6).
