### ISSUE TITLE
Language codes are not visible in the CC selection box

### ISSUE THREAD

**Issue by Natkeeran** [digitalutsc/islandora_solution_pack_oralhistories#54]
Adding a second webvtt file with the language code suffix _FR does cause the datastream to be available to closed captioning, but even when configured, the language codes are not visible in the CC selection box.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/digitalutsc/islandora_solution_pack_oralhistories/pull/62 (merged with commit https://github.com/digitalutsc/islandora_solution_pack_oralhistories/commit/5241ca1f5bca529eb3f9479fbb2074d38c0debbc).
