### ISSUE TITLE
Bootstrap themes do not need to use provided bootstrap css/js

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_solution_pack_oralhistories#57]
Need to provide documentation/instruction about removing the bootstrap css/js dependencies if you are using a Bootstrap themes (including Bootstrap business). There are issues if you decide to include bootstrap dependencies, e.g. clicking the transcript viewer to view the tiers doesn't work.

**Comment by kstapelfeldt** [comment]
Only in the readme. Kim to move to the wiki also.

**Comment by kimpham54** [comment]
done
