### ISSUE TITLE
Editing cues with escaped characters breaks the transcript XML

### ISSUE THREAD

**Issue by McFateM** [digitalutsc/islandora_solution_pack_oralhistories#58]
In my workflow I have a proofreader/editor who's encountered problems when editing changes to transcripts when using the "Edit" button and Transcript_UI (?) editor.  Specifically, when we embed escaped special characters in our transcript XML, for instance a string like "S&B" represented in the transcript as "S&amp;B", it displays "correctly" but when saved/submitted the XML is badly broken.  It appears that the "&amp;" character is translated back to "&" for display but it is then saved as such in the XML and invalidates that XML.  In some cases an entire cue following the changed character is lost.  The broken XML is produced even if no edits are performed, as long as the transcript is saved by clicking "Submit".

I have an example object at https://digital.grinnell.edu/islandora/object/grinnell%3A18500, but the parent collection is still dark and elevated permissions are required to view or edit it.

**Comment by MarcusBarnes** [comment]
I've reviewed and the fix appears to work as expected.  @kimpham54 Would you please confirm before I merge?  Thank you.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/digitalutsc/islandora_solution_pack_oralhistories/pull/60 (merged with commit https://github.com/digitalutsc/islandora_solution_pack_oralhistories/commit/18ec7ce5bcfbeab70d03553c2c098c659f15f33d). 

@McFateM You may want to pull and test the latest change.  Thanks again for noting the issue.
