### ISSUE TITLE
Add option to expand all cues in the Edit/Transcript_UI window

### ISSUE THREAD

**Issue by McFateM** [digitalutsc/islandora_solution_pack_oralhistories#59]
Not an issue, but an enhancement request...  In my workflow editors and proofreaders frequently wish to search for specific keywords in a transcript but find it difficult to do so because the Transcript_UI editor opens with all but the first cue collapsed.  An option to expand all cues for display/search would be a very welcome addition.

**Comment by MarcusBarnes** [comment]
@McFateM We've added a toggle all cues button in this pull-request https://github.com/digitalutsc/islandora_solution_pack_oralhistories/pull/93.  Would you please give the pull-request a quick test and see if it (partially) addresses your enhancement request?  Thank you in advance.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request #93 (merged with commit https://github.com/digitalutsc/islandora_solution_pack_oralhistories/commit/23e5289fb9f961d1e047e2cd2ff5ec027c391b3b).
