### ISSUE TITLE
Documentation:  CDATA sections in transcript XML

### ISSUE THREAD

**Issue by MarcusBarnes** [digitalutsc/islandora_solution_pack_oralhistories#63]
Related to discussions in pull-request https://github.com/digitalutsc/islandora_solution_pack_oralhistories/pull/60, update relevant documentation regarding the use of CDATA sections in transcript XML.

**Comment by kstapelfeldt** [comment]
Update sample transcripts to include the CDATA tag and an in-line comment explaining how and when CDATA tags are generated and why.

**Comment by kimpham54** [comment]
finished
