### ISSUE TITLE
compose_vtt_transcript_as_transcripts_ui uses file_get_contents to get datastream contents

### ISSUE THREAD

**Issue by wgilling** [digitalutsc/islandora_solution_pack_oralhistories#65]
compose_vtt_transcript_as_transcripts_ui() uses a URL to get the datastream contents of an object by using file_get_contents which does not work under some circumstances.  Perhaps that call using file_get_contents() could be fixed so that it always works, but the preferred method of getting the datastream contents would be to use the islandora object & datastream functions to get that value - similar to :

  $transcript_content = $islandora_object['TRANSCRIPT']->content;

Of course to achieve this, the $ui->options structure would need to be modified to provide the islandora object PID value as well as the transcript's datastream ID (DSID) should be passed into this function in order to create the object - and call the content method on the specific DSID.

**Comment by wgilling** [comment]
I wrote a quick branch that parses the given URL and uses the islandora functions to get the datastream content rather than makes a roundabout http request to get a value from fedora.  The branch is called ULS_replace_file_get_contents and I will make a pull request for it separately after I enter this comment.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/digitalutsc/islandora_solution_pack_oralhistories/pull/67 (merged with commit https://github.com/digitalutsc/islandora_solution_pack_oralhistories/commit/332bff333310fa331c32c6b4ea1d3a25f8cadb72).   Thank you @bgilling.
