### ISSUE TITLE
Oral history media + TRANSCRIPT xml upload creates blank CC option

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_solution_pack_oralhistories#69]
Description
Whenever a TRANSCRIPT (xml based) is uploaded, a blank option (the TRANSCRIPT datastream) that does not display captions is added to the CC options.

Steps to Reproduce
1. Add an audio/video file with TRANSCRIPT. Or just add an audio/video file then add a TRANSCRIPT after the original audio/video is ingested
2. View the oral history, go to CC

Expected Behaviour
A single option (taken from MEDIATRACK) for closed captioning gets created

Actual Behaviour
Two options for closed captioning gets created, an language option (taken from MEDIATRACK) and an option (taken from TRANSCRIPT) that does not have a name and does not display captions.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/digitalutsc/islandora_solution_pack_oralhistories/pull/79 (merged with commit https://github.com/digitalutsc/islandora_solution_pack_oralhistories/commit/d1f61a32759c583765463592dfd8c9586ffad615).  Thank you @kimpham54 @Natkeeran.
