### ISSUE TITLE
TRANSCRIPT xml upon upload assumes that original language is English

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_solution_pack_oralhistories#70]
Description
When a TRANSCRIPT xml is uploaded, content from <transcript> gets transformed into VTT for closed captioning and is indexed. The CC language options assumes it's an 'en' code. This still happens when options in /admin/islandora/solution_pack_config/oralhistories under 'Specify VTT default language code(s)' are changed (such as removing en, adding only fr). It would be nice to modify the language code somehow after ingest, or indicate what the language code is in the xml filename, similar to how it's done with additional MEDIATRACK vtt files and have that display as the language code in the closed captioning.

Steps to Reproduce
Upload audio/video with TRANSCRIPT xml. TRANSCRIPT xml has a <transcript> tier with non-english content

Expected Behaviour
Oral history is ingested, vtt for closed captioning gets created, go to CC in interface and you have the option to select closed captioning with the correct language code.

Actual Behaviour
Oral history is ingested, vtt for closed captioning gets created, go to CC in interface and you have the option to select closed captioning with 'en' language code.

**Comment by MarcusBarnes** [comment]
I can confirm that the 'Specify VTT default language code(s)' language code setting is not being honored when using only one default VTT language code.  I changed the language code from en to fr and en was used.

**Comment by Natkeeran** [comment]
Yes, English is set as default.  It should take the default language specified.  Is that correct?

**Comment by kimpham54** [comment]
@Natkeeran @MarcusBarnes  I think this is going to be a very common use case, where the original language isn't in english. Being able to specify the original language or being able to change the default en will be a desired feature

**Comment by MarcusBarnes** [comment]
As part of this discussion, it might be useful to update TRANSCRIPT XML syntax to record language codes.  This will make it possible to extract and create WebVTT files for each language code in the TRANSCRIPT XML.

**Comment by kimpham54** [comment]
use filename suffix for TRANSCRIPT vtt and TRANSCRIPT xml for consistency's sake and in the situation where <transcript> may have multiple languages (attributes)

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/digitalutsc/islandora_solution_pack_oralhistories/pull/88 (merged with commit https://github.com/digitalutsc/islandora_solution_pack_oralhistories/commit/5f84530a29564d947fa5475baec41db9712ef235).
