### ISSUE TITLE
Batch ingesting oral history audio files does not create audio oral history objects

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_solution_pack_oralhistories#72]
Description
Batch ingesting oral history media files does not work for batch audio files

Steps to reproduce
1. Batch import a zip of audio files, select Islandora Oral Histories Content Model

Expected behaviour
Audio objects get created and can be viewed in collection

Actual behaviour
Audio objects are not ingested properly

Error message when trying to view object:
```
Notice: Undefined index: url in include() (line 6 of /var/www/drupal/sites/all/modules/islandora_solution_pack_oralhistories/theme/islandora-html5-video-stack.tpl.php).
Notice: Undefined index: mime in include() (line 6 of /var/www/drupal/sites/all/modules/islandora_solution_pack_oralhistories/theme/islandora-html5-video-stack.tpl.php).
```

.mp3 file gets ingested into OBJ, recognized as an audio/mpeg. downloading datastream creates .mp2 file extension
MP4 derivative gets created (not audio)
MKV derivative gets created (not audio)

Notes
Ingest of video only oral histories works as expected.

**Comment by kstapelfeldt** [comment]
Once we have implemented a batch solution, we will test and report any emerging issues.
