### ISSUE TITLE
Hide transcript viewer if no transcript is available

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_solution_pack_oralhistories#73]
Option to hide transcript viewer if no transcript is available, instead of user being able to see the Transcript tab with "No Content available." text

**Comment by MarcusBarnes** [comment]
Possibly related to how this solution to https://github.com/digitalutsc/islandora_solution_pack_oralhistories/issues/37 was implemented - I'll investigate further.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/digitalutsc/islandora_solution_pack_oralhistories/pull/78 (merged with commit https://github.com/digitalutsc/islandora_solution_pack_oralhistories/commit/732701f31ffc159afac26fe73cf86ea78a965d76).
