### ISSUE TITLE
Multiple refreshes are required for editing through transcripts_ui

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_solution_pack_oralhistories#74]
Steps to Reproduce
1. With an oral history that has a transcript display, edit a cue that isn't <transcript> and Submit
2. View transcript display in object after one refresh

Expected Behaviour
Transcript tiers are updated in transcript display. 

Actual Behaviour
Transcript tiers that aren't <transcript> are not updated in transcript display. If you refresh 1-2 more times the transcript display is updated.

Notes
If you edit the transcript tier through the UI, it is updated when you refresh the object page once.

**Comment by Natkeeran** [comment]
Related to this PR : https://github.com/digitalutsc/islandora_solution_pack_oralhistories/pull/76

I think the delay is due to delay in solr indexing the xml datastream.  Not sure if we can totally avoid that.

**Comment by kstapelfeldt** [comment]
confirm that this is still an issue and document any remaining latency or requirements in wiki, and possibly in interface documentation.

**Comment by kimpham54** [comment]
done
