### ISSUE TITLE
create diagram of oral history ingest workflow

### ISSUE THREAD

**Issue by kimpham54** [digitalutsc/islandora_solution_pack_oralhistories#80]
create workflow diagram of SP functionality, derivative and datastream updates depending on what you ingest.

include:
- what happens if you edit through transcripts_ui (can't for TRANSCRIPT vtt, can for TRANSCRIPT xml, what datastreams get updated
- which datastream powers CC (TRANSCRIPT if vtt, MEDIATRACK if xml)
- when and when you do not need to use INDEXMEDIATRACK for solr
- when CDATA gets added

**Comment by kimpham54** [comment]
![oral histories transcript two workflows - jun8](https://user-images.githubusercontent.com/2915770/26939917-d924ba26-4c46-11e7-8191-2074a0907841.png)

**Comment by kimpham54** [comment]
added to wiki

**Comment by MarcusBarnes** [comment]
https://github.com/digitalutsc/islandora_solution_pack_oralhistories/wiki#ingest-behaviour-for-xml-vs-webvtt-transcripts
