### ISSUE TITLE
Transcript of audio-only OH no longer appears in the window

### ISSUE THREAD

**Issue by McFateM** [digitalutsc/islandora_solution_pack_oralhistories#83]
I recently upgraded to the current 7.x branch of the code and now the transcript of our audio-only oral histories no longer appears or scrolls in the top window pane.  The transcript appears below as it always did, but the scrolling text that previously appeared in the top window is now replaced by the object's thumbnail.  Note these are audio-only oral histories with no video content.

**Comment by McFateM** [comment]
Follow-up to this issue...   My latest pull was made this morning and it upgraded the IOH module to the 7.x branch of this commit:  https://github.com/digitalutsc/islandora_solution_pack_oralhistories/commit/d04f0a78ad0889ae1201af7e51e9c720f27c978d.

The image shown below is what the top/video window of our OH content used to look like...
![screen shot 2017-06-07 at 1 44 21 pm](https://user-images.githubusercontent.com/8472769/26895636-c5564aba-4b87-11e7-869c-98de3ca6350b.png)

Now, following the upgrade I see this instead...
![screen shot 2017-06-07 at 1 48 26 pm](https://user-images.githubusercontent.com/8472769/26895707-0c98cf06-4b88-11e7-80f0-c249c0fc02f0.png)

The datastreams for this particular piece of content look like this...
![screen shot 2017-06-07 at 1 49 43 pm](https://user-images.githubusercontent.com/8472769/26895852-8aae34e4-4b88-11e7-99f1-be3d1645aff4.png)

Perhaps I am missing a key datastream?  I have not reconfigured the module or regenerated any of the content derivatives yet, apart from running a trial regeneration of the MEDIATRACK datastream moments ago (and that appears to have had no effect).

**Comment by kimpham54** [comment]
@McFateM when you play the audio, are you able to see the captions at all? I have the latest 7.x and this is what I see when the audio file is played:
<img width="1110" alt="screen shot 2017-06-07 at 14 57 11" src="https://user-images.githubusercontent.com/2915770/26896121-c56ef9ca-4b91-11e7-99be-2f766800954c.png">




Can you send us your mediatrack datastream?

**Comment by MarcusBarnes** [comment]
When updating to the latest commits in the default branch from an older install, you will want to review the module's configuration settings after updating, pressing save in the interface to make sure that the configuration variables are stored.
