### ISSUE TITLE
Multiple derivative versiosn get created

### ISSUE THREAD

**Issue by Natkeeran** [digitalutsc/islandora_solution_pack_oralhistories#85]
When WebVTT derivative creation is enabled, whenever the xml gets edited two versions of the derivative vtt datastreams get created.  For each version, it also creates 2 versions of index datastreams as well.

## Steps to reproduce
* Enable derivative creation
* Ingest an xml transcript
* Verify that the versions are all number 1
* Edit the xml and save
* MEDIATRACK version goes to 3
* INDEXMEDIATRACK version goes to 5

## Expected
MEDIATRACK and INDEX should go to version 2

## Actual
Two versions of mediatrack gets created (version goes to 3).  And for each version, an indexmediatrack gets created (version goes to 5).

**Comment by kimpham54** [comment]
i was also able to reproduce the issue

**Comment by Natkeeran** [comment]
@kimpham54 Pls see if this https://github.com/digitalutsc/islandora_solution_pack_oralhistories/pull/87 fixes the issue.  Thanks.

**Comment by MarcusBarnes** [comment]
I'm currently testing https://github.com/digitalutsc/islandora_solution_pack_oralhistories/pull/87.  Thanks.  @kimpham54  You're welcome to test too.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/digitalutsc/islandora_solution_pack_oralhistories/pull/87 (merged with commit https://github.com/digitalutsc/islandora_solution_pack_oralhistories/commit/0dbe8a1e1dfb337d1cfd51d5196e454aa2138f68).
