### ISSUE TITLE
Captions and transcript display not available if Solr has not indexed the content

### ISSUE THREAD

**Issue by McFateM** [digitalutsc/islandora_solution_pack_oralhistories#94]
For whatever reason, when I ingest an oral history using this module my content is NOT automatically indexed in Solr.  Consequently, when the process tries to render captions and transcript for display I see only this...

![screen shot 2017-06-27 at 2 08 46 pm](https://user-images.githubusercontent.com/8472769/27605434-4df131ea-5b42-11e7-8e7c-2674068d1e9f.png)

...with no real indication that anything is wrong.

So I've added a couple lines of code to utilities.inc to issue a warning that no Solr document was found.  I'm currently forking the project so I can provide the code update in a proper pull request.

**Comment by kstapelfeldt** [comment]
Will review pull request, thank you!

**Comment by MarcusBarnes** [comment]
This issue was addressed in pull-request https://github.com/Islandora-Labs/islandora_solution_pack_oralhistories/pull/114, which has been merged.
