### ISSUE TITLE
Do we have tests for the issue of multiple WebVTTs for the OH solution pack?

### ISSUE THREAD

**Issue by kstapelfeldt** [digitalutsc/islandora_solution_pack_oralhistories#99]
1. to confirm indexing behaviour
2. to confirm display when multiple WebVTTs appear
Also, we seem to enforce ISO standards for language codes in the language of the admin config, but it's not clear to me that these are actually requirements. Do we have tests? should we test?

**Comment by kstapelfeldt** [comment]
We do not enforce and need to ensure interface documentation is clear that this is a suggestion based on a convention that is prominent in the community. Arbitrary values are still accepted, so long as they match in the interface configuration panels.

**Comment by kimpham54** [comment]
done
